dbt_olist:
  target: dev
  outputs:
    dev:
      type: postgres
      host: de_psql
      port: 5432
      user: admin
      password: admin
      dbname: postgres
      schema: warehouse
      threads: 4
