name: 'dbt_olist'
version: '1.0.0'

profile: 'dbt_olist'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_olist:
    staging:
      +materialized: view          # Views — nhẹ, luôn fresh, không tốn storage
      +schema: staging_dbt
    intermediate:
      +materialized: ephemeral     # Ephemeral — chỉ tồn tại như CTE, không tạo object trong DB
    marts:
      +materialized: table         # Tables — persist data, sẵn sàng cho BI tools
      +schema: warehouse
